# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    serializer_listener.material:
        class: AppBundle\Serializer\Listener\MaterialListener
        tags:
            - { name: jms_serializer.event_subscriber }
    serializer_handler.materail:
        class: AppBundle\Serializer\Handler\MaterialHandler
        tags:
            - { name: jms_serializer.subscribing_handler }     